### PR TITLE
Add ResourceLink optional property to SupportingResource 

### PR DESCRIPTION
**Pull request by archi3315**
ONIX 3 standard supports ResourceLink XML element inside SupportingResource

### CODE REVIEW

**Comment by archi3315** [comment]
@zach-m could you consider to add this and do a minor release?

**Comment by zach-m** [comment]
Thanks for your contribution. However, your merge request edits an auto-generated file, so this is not the way to go. Let me look at the specs of ONIX3 and get back to you

**Comment by zach-m** [comment]
@archi3315 please double check with your providers.
According to ONIX official documentation, there's no `<ResourceLink>` directly under `<SupportingResource>`. It's available indirectly under `<ResourceVersion>`.

The structure is as follows:
```
<SupportingResource>
. <ResourceContentType>
. <ContentAudience>
. <Territory>
. . <CountriesIncluded>
. . <RegionsIncluded>
. . <CountriesExcluded>
. . <RegionsExcluded>
. <ResourceMode>
. <ResourceFeature>
. . <Resource​FeatureType>
. . <FeatureValue>
. . <FeatureNote>
. <ResourceVersion>
. . <ResourceForm>
. . <ResourceVersion​Feature>
. . . <ResourceVersion​FeatureType>
. . . <FeatureValue>
. . . <FeatureNote>
. . <ResourceLink>
. . <ContentDate>
. . . <ContentDateRole>
. . . <DateFormat>
. . . <Date>
```

For more details download the specs from <https://www.editeur.org/files/ONIX%203/ONIX_for_Books_Release3-0_html_Best_Practice+codes_Issue_45_v1-5-2.zip> and take a look at paragraph 16 of `ONIX_for_Books_Format_Specification_3.0.6.html`.

**Comment by archi3315** [comment]
You are right @zach-m. Thanks!

**Pull request closed without merging**
